import * as path from "path";
import * as fs from "fs-extra";
import { SpecDSL } from "./dsl-types";
import { buildEndpointFixture } from "./mock/fixtures";
import { generateProxyConfig } from "./mock/proxy";

// Re-export public symbols for backward compatibility
export {
  applyMockProxy,
  restoreMockProxy,
  startMockServerBackground,
  saveMockServerPid,
  ProxyApplyResult,
} from "./mock/proxy";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface MockServerOptions {
  /** Port for the mock server (default: 3001) */
  port?: number;
  /** Generate MSW handlers file */
  msw?: boolean;
  /** Generate frontend proxy config */
  proxy?: boolean;
  /** Output directory for generated files (default: mock/) */
  outputDir?: string;
}

export interface MockGenerationResult {
  files: Array<{ path: string; description: string }>;
}

// ─── Express Mock Server Generator ───────────────────────────────────────────

function generateMockServerJs(dsl: SpecDSL, port: number): string {
  const lines: string[] = [];

  lines.push(`// ─── Mock Server ─────────────────────────────────────────────`);
  lines.push(`// Auto-generated by ai-spec mock`);
  lines.push(`// Feature: ${dsl.feature.title}`);
  lines.push(`// DO NOT use in production. Standalone dev mock only.`);
  lines.push(``);
  lines.push(`const express = require('express');`);
  lines.push(`const app = express();`);
  lines.push(``);
  lines.push(`app.use(express.json());`);
  lines.push(``);
  lines.push(`// ─── CORS (dev only) ─────────────────────────────────────────`);
  lines.push(`app.use((req, res, next) => {`);
  lines.push(`  res.setHeader('Access-Control-Allow-Origin', '*');`);
  lines.push(`  res.setHeader('Access-Control-Allow-Methods', 'GET,POST,PUT,PATCH,DELETE,OPTIONS');`);
  lines.push(`  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');`);
  lines.push(`  if (req.method === 'OPTIONS') return res.sendStatus(204);`);
  lines.push(`  next();`);
  lines.push(`});`);
  lines.push(``);

  // Auth middleware
  const hasAuthEndpoints = dsl.endpoints.some((e) => e.auth);
  if (hasAuthEndpoints) {
    lines.push(`// ─── Auth check (returns 401 if Authorization header missing) ──`);
    lines.push(`function requireAuth(req, res, next) {`);
    lines.push(`  const authHeader = req.headers['authorization'];`);
    lines.push(`  if (!authHeader || !authHeader.startsWith('Bearer ')) {`);
    lines.push(`    return res.status(401).json({ code: 'UNAUTHORIZED', message: 'Missing or invalid Authorization header' });`);
    lines.push(`  }`);
    lines.push(`  next();`);
    lines.push(`}`);
    lines.push(``);
  }

  lines.push(`// ─── Routes ──────────────────────────────────────────────────`);

  for (const endpoint of dsl.endpoints) {
    const fixture = buildEndpointFixture(endpoint, dsl);
    const fixtureJson = JSON.stringify(fixture, null, 2)
      .split("\n")
      .map((l, i) => (i === 0 ? l : `    ${l}`))
      .join("\n");

    const expressMethod = endpoint.method.toLowerCase();
    // Convert DSL path params :param to express :param (already compatible)
    const expressPath = endpoint.path;

    lines.push(`// ${endpoint.id}: ${endpoint.description}`);
    if (endpoint.auth) {
      lines.push(`app.${expressMethod}('${expressPath}', requireAuth, (req, res) => {`);
    } else {
      lines.push(`app.${expressMethod}('${expressPath}', (req, res) => {`);
    }

    if (fixture === null) {
      lines.push(`  res.sendStatus(${endpoint.successStatus});`);
    } else {
      lines.push(`  res.status(${endpoint.successStatus}).json(${fixtureJson});`);
    }

    // Error simulation query param: ?simulate_error=ERRORCODE
    if (endpoint.errors && endpoint.errors.length > 0) {
      const firstError = endpoint.errors[0];
      lines.push(`  // Simulate error: GET /this/path?simulate_error=${firstError.code}`);
    }

    lines.push(`});`);
    lines.push(``);
  }

  lines.push(`// ─── Start ───────────────────────────────────────────────────`);
  lines.push(`const PORT = process.env.MOCK_PORT || ${port};`);
  lines.push(`app.listen(PORT, () => {`);
  lines.push(`  console.log(\`[ai-spec mock] Mock server running at http://localhost:\${PORT}\`);`);
  lines.push(`  console.log('[ai-spec mock] Endpoints:');`);
  for (const endpoint of dsl.endpoints) {
    lines.push(`  console.log('  ${endpoint.method.padEnd(7)} ${endpoint.path}');`);
  }
  lines.push(`});`);
  lines.push(``);

  return lines.join("\n");
}

// ─── MSW Handler Generator ────────────────────────────────────────────────────

function generateMswHandlers(dsl: SpecDSL): string {
  const lines: string[] = [];

  lines.push(`// ─── MSW Handlers ────────────────────────────────────────────`);
  lines.push(`// Auto-generated by ai-spec mock --msw`);
  lines.push(`// Feature: ${dsl.feature.title}`);
  lines.push(`// Place this file at: src/mocks/handlers.ts`);
  lines.push(``);
  lines.push(`import { http, HttpResponse } from 'msw';`);
  lines.push(``);

  for (const endpoint of dsl.endpoints) {
    const fixture = buildEndpointFixture(endpoint, dsl);
    const fixtureJson = JSON.stringify(fixture, null, 4)
      .split("\n")
      .map((l, i) => (i === 0 ? l : `    ${l}`))
      .join("\n");
    const method = endpoint.method.toLowerCase();
    lines.push(`// ${endpoint.id}: ${endpoint.description}`);
    if (fixture === null) {
      lines.push(`http.${method}('${endpoint.path}', () => {`);
      lines.push(`  return new HttpResponse(null, { status: ${endpoint.successStatus} });`);
    } else {
      lines.push(`http.${method}('${endpoint.path}', () => {`);
      lines.push(`  return HttpResponse.json(${fixtureJson}, { status: ${endpoint.successStatus} });`);
    }
    lines.push(`}),`);
    lines.push(``);
  }

  // Wrap in export
  const handlerLines = lines.join("\n");

  return `// ─── MSW Handlers ────────────────────────────────────────────
// Auto-generated by ai-spec mock --msw
// Feature: ${dsl.feature.title}
// Place this file at: src/mocks/handlers.ts

import { http, HttpResponse } from 'msw';

export const handlers = [
${dsl.endpoints
  .map((endpoint) => {
    const fixture = buildEndpointFixture(endpoint, dsl);
    const method = endpoint.method.toLowerCase();
    const indent = "  ";
    const fixtureJson = JSON.stringify(fixture, null, 2)
      .split("\n")
      .map((l, i) => (i === 0 ? l : `${indent}    ${l}`))
      .join("\n");

    const comment = `${indent}// ${endpoint.id}: ${endpoint.description}`;
    let handler: string;
    if (fixture === null) {
      handler = `${indent}http.${method}('${endpoint.path}', () => {\n${indent}  return new HttpResponse(null, { status: ${endpoint.successStatus} });\n${indent}})`;
    } else {
      handler = `${indent}http.${method}('${endpoint.path}', () => {\n${indent}  return HttpResponse.json(${fixtureJson}, { status: ${endpoint.successStatus} });\n${indent}})`;
    }
    return `${comment}\n${handler}`;
  })
  .join(",\n\n")}
];
`;
}

function generateMswBrowser(): string {
  return `// src/mocks/browser.ts
// MSW browser setup — import and call start() in your app entry point (dev only)
import { setupWorker } from 'msw/browser';
import { handlers } from './handlers';

export const worker = setupWorker(...handlers);
`;
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Generate mock server, proxy config, and/or MSW handlers from a SpecDSL.
 * Writes files relative to projectDir.
 */
export async function generateMockAssets(
  dsl: SpecDSL,
  projectDir: string,
  opts: MockServerOptions = {}
): Promise<MockGenerationResult> {
  const port = opts.port ?? 3001;
  const outputDir = path.join(projectDir, opts.outputDir ?? "mock");
  const result: MockGenerationResult = { files: [] };

  await fs.ensureDir(outputDir);

  // 1. Express mock server (always generated)
  const serverJs = generateMockServerJs(dsl, port);
  const serverPath = path.join(outputDir, "server.js");
  await fs.writeFile(serverPath, serverJs, "utf-8");
  result.files.push({
    path: path.relative(projectDir, serverPath),
    description: `Express mock server — run with: node mock/server.js`,
  });

  // README inside mock/
  const mockReadme = `# Mock Server

Auto-generated by \`ai-spec mock\` for **${dsl.feature.title}**.

## Quick start

\`\`\`bash
# Install express (one-time)
npm install --save-dev express

# Start the mock server
node mock/server.js
# → Listening on http://localhost:${port}
\`\`\`

## Endpoints

| Method | Path | Auth | Status |
|--------|------|------|--------|
${dsl.endpoints
  .map(
    (e) =>
      `| ${e.method} | \`${e.path}\` | ${e.auth ? "✓" : "—"} | ${e.successStatus} |`
  )
  .join("\n")}

## Error simulation

Append \`?simulate_error=1\` to any request to test error handling (not yet auto-wired — edit server.js manually).
`;
  const readmePath = path.join(outputDir, "README.md");
  await fs.writeFile(readmePath, mockReadme, "utf-8");
  result.files.push({
    path: path.relative(projectDir, readmePath),
    description: "Mock server usage guide",
  });

  // 2. Proxy config (optional)
  if (opts.proxy) {
    const { content, filename } = generateProxyConfig(dsl, port, projectDir);
    const proxyPath = path.join(projectDir, filename);
    await fs.ensureDir(path.dirname(proxyPath));
    await fs.writeFile(proxyPath, content, "utf-8");
    result.files.push({
      path: filename,
      description: "Proxy config snippet — copy instructions into your framework config",
    });
  }

  // 3. MSW handlers (optional)
  if (opts.msw) {
    const mswDir = path.join(projectDir, "src", "mocks");
    await fs.ensureDir(mswDir);

    const handlersContent = generateMswHandlers(dsl);
    const handlersPath = path.join(mswDir, "handlers.ts");
    await fs.writeFile(handlersPath, handlersContent, "utf-8");
    result.files.push({
      path: path.relative(projectDir, handlersPath),
      description: "MSW request handlers",
    });

    const browserContent = generateMswBrowser();
    const browserPath = path.join(mswDir, "browser.ts");
    await fs.writeFile(browserPath, browserContent, "utf-8");
    result.files.push({
      path: path.relative(projectDir, browserPath),
      description: "MSW browser worker setup",
    });
  }

  return result;
}

/**
 * Find the latest DSL file in a project directory.
 * Looks for *.dsl.json files under .ai-spec/
 */
export async function findLatestDslFile(projectDir: string): Promise<string | null> {
  const specDir = path.join(projectDir, ".ai-spec");
  if (!(await fs.pathExists(specDir))) return null;

  const allFiles: string[] = [];

  async function scan(dir: string): Promise<void> {
    const entries = await fs.readdir(dir);
    for (const entry of entries) {
      const abs = path.join(dir, entry);
      const stat = await fs.stat(abs);
      if (stat.isDirectory()) {
        await scan(abs);
      } else if (entry.endsWith(".dsl.json")) {
        allFiles.push(abs);
      }
    }
  }

  await scan(specDir);

  if (allFiles.length === 0) return null;

  // Return most recently modified
  const withMtimes = await Promise.all(
    allFiles.map(async (f) => ({ f, mtime: (await fs.stat(f)).mtime }))
  );
  withMtimes.sort((a, b) => b.mtime.getTime() - a.mtime.getTime());
  return withMtimes[0].f;
}
