import * as path from "path";
import * as fs from "fs-extra";
import { spawn } from "child_process";
import { SpecDSL, ApiEndpoint, FieldMap } from "./dsl-types";

// ─── Types ────────────────────────────────────────────────────────────────────

export interface MockServerOptions {
  /** Port for the mock server (default: 3001) */
  port?: number;
  /** Generate MSW handlers file */
  msw?: boolean;
  /** Generate frontend proxy config */
  proxy?: boolean;
  /** Output directory for generated files (default: mock/) */
  outputDir?: string;
}

export interface MockGenerationResult {
  files: Array<{ path: string; description: string }>;
}

// ─── Fixture Generator ────────────────────────────────────────────────────────

/**
 * Convert a type-description string to a fixture value (JavaScript literal).
 */
function typeToFixture(fieldName: string, typeDesc: string): unknown {
  const t = typeDesc.toLowerCase();

  if (t.includes("boolean") || t === "bool") return true;
  if (t.includes("int") || t.includes("number") || t.includes("float") || t.includes("decimal")) {
    if (fieldName.toLowerCase().includes("id")) return 1;
    if (fieldName.toLowerCase().includes("count") || fieldName.toLowerCase().includes("total")) return 42;
    if (fieldName.toLowerCase().includes("price") || fieldName.toLowerCase().includes("amount")) return 9.99;
    return 1;
  }
  if (t.includes("datetime") || t.includes("date") || t.includes("timestamp")) {
    return "2024-01-15T10:30:00.000Z";
  }
  if (t.includes("[]") || t.includes("array") || t.includes("list")) return [];
  if (t.includes("object") || t.includes("json") || t.includes("record")) return {};

  // String heuristics by field name
  const name = fieldName.toLowerCase();
  if (name === "id" || name.endsWith("id")) return "abc123";
  if (name.includes("email")) return "user@example.com";
  if (name.includes("phone")) return "+1-555-0100";
  if (name.includes("url") || name.includes("image") || name.includes("avatar")) return "https://example.com/sample.jpg";
  if (name.includes("token") || name.includes("secret")) return "mock-token-xyz";
  if (name.includes("name")) return "Example Name";
  if (name.includes("title")) return "Example Title";
  if (name.includes("description") || name.includes("content") || name.includes("body")) return "Example description text";
  if (name.includes("status")) return "active";
  if (name.includes("type") || name.includes("role")) return "default";
  if (name.includes("code")) return "CODE001";

  return `example_${fieldName}`;
}

function buildFixtureObject(fields: FieldMap): Record<string, unknown> {
  const obj: Record<string, unknown> = {};
  for (const [name, type] of Object.entries(fields)) {
    obj[name] = typeToFixture(name, type);
  }
  return obj;
}

/**
 * Build a fixture response object for an endpoint.
 * For endpoints without explicit response schemas, generate minimal fixtures from model context.
 */
function buildEndpointFixture(endpoint: ApiEndpoint, dsl: SpecDSL): unknown {
  const method = endpoint.method;
  const status = endpoint.successStatus;

  // DELETE with 204 → no body
  if (status === 204) return null;

  // Try to derive fixture from model names mentioned in endpoint description
  const descLower = endpoint.description.toLowerCase();
  const matchedModel = dsl.models.find((m) =>
    descLower.includes(m.name.toLowerCase())
  );

  if (matchedModel) {
    const fields: FieldMap = {};
    for (const f of matchedModel.fields) {
      fields[f.name] = f.type;
    }
    const item = buildFixtureObject(fields);

    // List endpoints return arrays
    if (method === "GET" && (descLower.includes("list") || descLower.includes("all") || descLower.includes("paginate"))) {
      return {
        data: [item, { ...item, id: "def456" }],
        total: 2,
        page: 1,
        pageSize: 10,
      };
    }
    return { data: item };
  }

  // Fallback based on method
  if (method === "POST") return { data: { id: "abc123", createdAt: "2024-01-15T10:30:00.000Z" } };
  if (method === "GET") return { data: { id: "abc123" } };
  return { success: true };
}

// ─── Express Mock Server Generator ───────────────────────────────────────────

function generateMockServerJs(dsl: SpecDSL, port: number): string {
  const lines: string[] = [];

  lines.push(`// ─── Mock Server ─────────────────────────────────────────────`);
  lines.push(`// Auto-generated by ai-spec mock`);
  lines.push(`// Feature: ${dsl.feature.title}`);
  lines.push(`// DO NOT use in production. Standalone dev mock only.`);
  lines.push(``);
  lines.push(`const express = require('express');`);
  lines.push(`const app = express();`);
  lines.push(``);
  lines.push(`app.use(express.json());`);
  lines.push(``);
  lines.push(`// ─── CORS (dev only) ─────────────────────────────────────────`);
  lines.push(`app.use((req, res, next) => {`);
  lines.push(`  res.setHeader('Access-Control-Allow-Origin', '*');`);
  lines.push(`  res.setHeader('Access-Control-Allow-Methods', 'GET,POST,PUT,PATCH,DELETE,OPTIONS');`);
  lines.push(`  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');`);
  lines.push(`  if (req.method === 'OPTIONS') return res.sendStatus(204);`);
  lines.push(`  next();`);
  lines.push(`});`);
  lines.push(``);

  // Auth middleware
  const hasAuthEndpoints = dsl.endpoints.some((e) => e.auth);
  if (hasAuthEndpoints) {
    lines.push(`// ─── Auth check (returns 401 if Authorization header missing) ──`);
    lines.push(`function requireAuth(req, res, next) {`);
    lines.push(`  const authHeader = req.headers['authorization'];`);
    lines.push(`  if (!authHeader || !authHeader.startsWith('Bearer ')) {`);
    lines.push(`    return res.status(401).json({ code: 'UNAUTHORIZED', message: 'Missing or invalid Authorization header' });`);
    lines.push(`  }`);
    lines.push(`  next();`);
    lines.push(`}`);
    lines.push(``);
  }

  lines.push(`// ─── Routes ──────────────────────────────────────────────────`);

  for (const endpoint of dsl.endpoints) {
    const fixture = buildEndpointFixture(endpoint, dsl);
    const fixtureJson = JSON.stringify(fixture, null, 2)
      .split("\n")
      .map((l, i) => (i === 0 ? l : `    ${l}`))
      .join("\n");

    const expressMethod = endpoint.method.toLowerCase();
    // Convert DSL path params :param to express :param (already compatible)
    const expressPath = endpoint.path;

    lines.push(`// ${endpoint.id}: ${endpoint.description}`);
    if (endpoint.auth) {
      lines.push(`app.${expressMethod}('${expressPath}', requireAuth, (req, res) => {`);
    } else {
      lines.push(`app.${expressMethod}('${expressPath}', (req, res) => {`);
    }

    if (fixture === null) {
      lines.push(`  res.sendStatus(${endpoint.successStatus});`);
    } else {
      lines.push(`  res.status(${endpoint.successStatus}).json(${fixtureJson});`);
    }

    // Error simulation query param: ?simulate_error=ERRORCODE
    if (endpoint.errors && endpoint.errors.length > 0) {
      const firstError = endpoint.errors[0];
      lines.push(`  // Simulate error: GET /this/path?simulate_error=${firstError.code}`);
    }

    lines.push(`});`);
    lines.push(``);
  }

  lines.push(`// ─── Start ───────────────────────────────────────────────────`);
  lines.push(`const PORT = process.env.MOCK_PORT || ${port};`);
  lines.push(`app.listen(PORT, () => {`);
  lines.push(`  console.log(\`[ai-spec mock] Mock server running at http://localhost:\${PORT}\`);`);
  lines.push(`  console.log('[ai-spec mock] Endpoints:');`);
  for (const endpoint of dsl.endpoints) {
    lines.push(`  console.log('  ${endpoint.method.padEnd(7)} ${endpoint.path}');`);
  }
  lines.push(`});`);
  lines.push(``);

  return lines.join("\n");
}

// ─── Proxy Config Generators ──────────────────────────────────────────────────

function detectFrontendFramework(projectDir: string): "vite" | "next" | "webpack" | "cra" | "unknown" {
  // Check vite.config
  for (const f of ["vite.config.ts", "vite.config.js", "vite.config.mts"]) {
    if (fs.existsSync(path.join(projectDir, f))) return "vite";
  }
  // Check next.config
  for (const f of ["next.config.js", "next.config.ts", "next.config.mjs"]) {
    if (fs.existsSync(path.join(projectDir, f))) return "next";
  }
  // Check for CRA (react-scripts in package.json)
  const pkgPath = path.join(projectDir, "package.json");
  if (fs.existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
      const deps = { ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) };
      if (deps["react-scripts"]) return "cra";
    } catch { /* ignore */ }
  }
  // Check webpack.config
  for (const f of ["webpack.config.js", "webpack.config.ts"]) {
    if (fs.existsSync(path.join(projectDir, f))) return "webpack";
  }
  return "unknown";
}

function generateViteProxyBlock(mockPort: number, endpoints: ApiEndpoint[]): string {
  // Collect unique path prefixes
  const prefixes = new Set<string>();
  for (const ep of endpoints) {
    const parts = ep.path.split("/").filter(Boolean);
    if (parts.length > 0) prefixes.add(`/${parts[0]}`);
  }
  const target = `http://localhost:${mockPort}`;
  const proxyEntries = Array.from(prefixes)
    .map((p) => `    '${p}': { target: '${target}', changeOrigin: true }`)
    .join(",\n");

  return `// Add this proxy block to your vite.config.ts / vite.config.js
// Inside the defineConfig({ server: { proxy: { ... } } }) section:
//
// server: {
//   proxy: {
${proxyEntries
  .split("\n")
  .map((l) => `//   ${l}`)
  .join("\n")}
//   }
// }

// ─── Standalone proxy snippet for vite.config.ts ─────────────────────────────
// import { defineConfig } from 'vite';
// export default defineConfig({
//   server: {
//     proxy: {
${proxyEntries
  .split("\n")
  .map((l) => `//       ${l.trim()}`)
  .join("\n")}
//     }
//   }
// });
`;
}

function generateNextProxyBlock(mockPort: number, endpoints: ApiEndpoint[]): string {
  const prefixes = new Set<string>();
  for (const ep of endpoints) {
    const parts = ep.path.split("/").filter(Boolean);
    if (parts.length > 0) prefixes.add(`/${parts[0]}`);
  }
  const rewrites = Array.from(prefixes).map(
    (p) => `    { source: '${p}/:path*', destination: 'http://localhost:${mockPort}${p}/:path*' }`
  );

  return `// Add this to your next.config.js rewrites():
//
// module.exports = {
//   async rewrites() {
//     return [
${rewrites.map((r) => `//       ${r}`).join(",\n")}
//     ];
//   },
// };
`;
}

function generateWebpackProxyBlock(mockPort: number, endpoints: ApiEndpoint[]): string {
  const prefixes = new Set<string>();
  for (const ep of endpoints) {
    const parts = ep.path.split("/").filter(Boolean);
    if (parts.length > 0) prefixes.add(`/${parts[0]}`);
  }
  const proxyEntries = Array.from(prefixes)
    .map(
      (p) =>
        `    '${p}': {\n      target: 'http://localhost:${mockPort}',\n      changeOrigin: true\n    }`
    )
    .join(",\n");

  return `// Add this to your webpack.config.js devServer.proxy section:
//
// devServer: {
//   proxy: {
${proxyEntries
  .split("\n")
  .map((l) => `//   ${l}`)
  .join("\n")}
//   }
// }
`;
}

function generateCraProxyBlock(mockPort: number): string {
  return `// For Create React App: add a "proxy" field to package.json
// This only proxies requests that don't match static files:
//
// {
//   "proxy": "http://localhost:${mockPort}"
// }
//
// Or use src/setupProxy.js for per-path control:
// const { createProxyMiddleware } = require('http-proxy-middleware');
// module.exports = function(app) {
//   app.use('/api', createProxyMiddleware({ target: 'http://localhost:${mockPort}', changeOrigin: true }));
// };
`;
}

function generateProxyConfig(
  dsl: SpecDSL,
  mockPort: number,
  projectDir: string
): { content: string; filename: string } {
  const framework = detectFrontendFramework(projectDir);

  switch (framework) {
    case "vite":
      return {
        filename: "mock/proxy.vite.comment.txt",
        content: generateViteProxyBlock(mockPort, dsl.endpoints),
      };
    case "next":
      return {
        filename: "mock/proxy.next.comment.txt",
        content: generateNextProxyBlock(mockPort, dsl.endpoints),
      };
    case "cra":
      return {
        filename: "mock/proxy.cra.comment.txt",
        content: generateCraProxyBlock(mockPort),
      };
    default:
      return {
        filename: "mock/proxy.webpack.comment.txt",
        content: generateWebpackProxyBlock(mockPort, dsl.endpoints),
      };
  }
}

// ─── MSW Handler Generator ────────────────────────────────────────────────────

function generateMswHandlers(dsl: SpecDSL): string {
  const lines: string[] = [];

  lines.push(`// ─── MSW Handlers ────────────────────────────────────────────`);
  lines.push(`// Auto-generated by ai-spec mock --msw`);
  lines.push(`// Feature: ${dsl.feature.title}`);
  lines.push(`// Place this file at: src/mocks/handlers.ts`);
  lines.push(``);
  lines.push(`import { http, HttpResponse } from 'msw';`);
  lines.push(``);

  for (const endpoint of dsl.endpoints) {
    const fixture = buildEndpointFixture(endpoint, dsl);
    const fixtureJson = JSON.stringify(fixture, null, 4)
      .split("\n")
      .map((l, i) => (i === 0 ? l : `    ${l}`))
      .join("\n");
    const method = endpoint.method.toLowerCase();
    lines.push(`// ${endpoint.id}: ${endpoint.description}`);
    if (fixture === null) {
      lines.push(`http.${method}('${endpoint.path}', () => {`);
      lines.push(`  return new HttpResponse(null, { status: ${endpoint.successStatus} });`);
    } else {
      lines.push(`http.${method}('${endpoint.path}', () => {`);
      lines.push(`  return HttpResponse.json(${fixtureJson}, { status: ${endpoint.successStatus} });`);
    }
    lines.push(`}),`);
    lines.push(``);
  }

  // Wrap in export
  const handlerLines = lines.join("\n");

  return `// ─── MSW Handlers ────────────────────────────────────────────
// Auto-generated by ai-spec mock --msw
// Feature: ${dsl.feature.title}
// Place this file at: src/mocks/handlers.ts

import { http, HttpResponse } from 'msw';

export const handlers = [
${dsl.endpoints
  .map((endpoint) => {
    const fixture = buildEndpointFixture(endpoint, dsl);
    const method = endpoint.method.toLowerCase();
    const indent = "  ";
    const fixtureJson = JSON.stringify(fixture, null, 2)
      .split("\n")
      .map((l, i) => (i === 0 ? l : `${indent}    ${l}`))
      .join("\n");

    const comment = `${indent}// ${endpoint.id}: ${endpoint.description}`;
    let handler: string;
    if (fixture === null) {
      handler = `${indent}http.${method}('${endpoint.path}', () => {\n${indent}  return new HttpResponse(null, { status: ${endpoint.successStatus} });\n${indent}})`;
    } else {
      handler = `${indent}http.${method}('${endpoint.path}', () => {\n${indent}  return HttpResponse.json(${fixtureJson}, { status: ${endpoint.successStatus} });\n${indent}})`;
    }
    return `${comment}\n${handler}`;
  })
  .join(",\n\n")}
];
`;
}

function generateMswBrowser(): string {
  return `// src/mocks/browser.ts
// MSW browser setup — import and call start() in your app entry point (dev only)
import { setupWorker } from 'msw/browser';
import { handlers } from './handlers';

export const worker = setupWorker(...handlers);
`;
}

// ─── Proxy Patching (applyMockProxy / restoreMockProxy) ──────────────────────

const MOCK_LOCK_FILE = ".ai-spec-mock.lock.json";

interface MockLock {
  framework: string;
  mockPort: number;
  frontendDir: string;
  mockServerPid?: number;
  actions: Array<
    | { type: "wrote-file"; filePath: string }
    | { type: "patched-pkg-proxy"; originalProxy?: string | null }
    | { type: "added-pkg-script"; key: string; originalValue?: string | null }
  >;
}

export interface ProxyApplyResult {
  framework: string;
  applied: boolean;
  devCommand: string | null;
  note?: string;
}

function findViteConfigFile(projectDir: string): string | null {
  for (const f of ["vite.config.ts", "vite.config.mts", "vite.config.js", "vite.config.mjs"]) {
    if (fs.existsSync(path.join(projectDir, f))) return f;
  }
  return null;
}

function buildViteProxyEntries(endpoints: ApiEndpoint[], mockPort: number): string {
  const prefixes = new Set<string>();
  for (const ep of endpoints) {
    const parts = ep.path.split("/").filter(Boolean);
    if (parts.length > 0) prefixes.add(`/${parts[0]}`);
  }
  if (prefixes.size === 0) prefixes.add("/api");
  const target = `http://localhost:${mockPort}`;
  return Array.from(prefixes)
    .map((p) => `        '${p}': { target: '${target}', changeOrigin: true },`)
    .join("\n");
}

function generateViteMockConfigTs(baseConfigFile: string, mockPort: number, endpoints: ApiEndpoint[]): string {
  const importPath = `./${baseConfigFile.replace(/\.(ts|mts|js|mjs)$/, "")}`;
  const proxyEntries = buildViteProxyEntries(endpoints, mockPort);
  return `// Auto-generated by ai-spec mock --serve
// LOCAL DEVELOPMENT ONLY — do not commit this file
// Remove with: ai-spec mock --restore
import { defineConfig, mergeConfig } from 'vite';

export default defineConfig(async (env) => {
  const mod = await import('${importPath}');
  const baseConfigOrFn = mod.default;
  const baseConfig =
    typeof baseConfigOrFn === 'function'
      ? await baseConfigOrFn(env)
      : baseConfigOrFn;

  return mergeConfig(baseConfig ?? {}, {
    server: {
      proxy: {
${proxyEntries}
      },
    },
  });
});
`;
}

/**
 * Patch the frontend project's proxy config to point to the mock server.
 * Vite: writes vite.config.ai-spec-mock.ts + adds "dev:mock" npm script.
 * CRA : patches package.json "proxy" field (original backed up in lock file).
 * Saves .ai-spec-mock.lock.json so restoreMockProxy() can undo all changes.
 */
export async function applyMockProxy(
  frontendDir: string,
  mockPort: number,
  endpoints: ApiEndpoint[] = []
): Promise<ProxyApplyResult> {
  const framework = detectFrontendFramework(frontendDir);
  const actions: MockLock["actions"] = [];

  if (framework === "vite") {
    const viteConfigFile = findViteConfigFile(frontendDir) ?? "vite.config.ts";
    const mockConfigContent = generateViteMockConfigTs(viteConfigFile, mockPort, endpoints);
    const mockConfigPath = path.join(frontendDir, "vite.config.ai-spec-mock.ts");
    await fs.writeFile(mockConfigPath, mockConfigContent, "utf-8");
    actions.push({ type: "wrote-file", filePath: "vite.config.ai-spec-mock.ts" });

    const pkgPath = path.join(frontendDir, "package.json");
    if (await fs.pathExists(pkgPath)) {
      const pkg = await fs.readJson(pkgPath);
      pkg.scripts = pkg.scripts ?? {};
      const originalValue: string | null = pkg.scripts["dev:mock"] ?? null;
      pkg.scripts["dev:mock"] = "vite --config vite.config.ai-spec-mock.ts";
      await fs.writeJson(pkgPath, pkg, { spaces: 2 });
      actions.push({ type: "added-pkg-script", key: "dev:mock", originalValue });
    }

    const lock: MockLock = { framework, mockPort, frontendDir, actions };
    await fs.writeJson(path.join(frontendDir, MOCK_LOCK_FILE), lock, { spaces: 2 });
    return { framework, applied: true, devCommand: "npm run dev:mock" };
  }

  if (framework === "cra") {
    const pkgPath = path.join(frontendDir, "package.json");
    if (await fs.pathExists(pkgPath)) {
      const pkg = await fs.readJson(pkgPath);
      const originalProxy: string | null = pkg.proxy ?? null;
      pkg.proxy = `http://localhost:${mockPort}`;
      await fs.writeJson(pkgPath, pkg, { spaces: 2 });
      actions.push({ type: "patched-pkg-proxy", originalProxy });
      const lock: MockLock = { framework, mockPort, frontendDir, actions };
      await fs.writeJson(path.join(frontendDir, MOCK_LOCK_FILE), lock, { spaces: 2 });
      return { framework, applied: true, devCommand: "npm start" };
    }
    return { framework, applied: false, devCommand: null, note: "No package.json found." };
  }

  // next / webpack / unknown — save lock but no auto-patch
  const lock: MockLock = { framework, mockPort, frontendDir, actions };
  await fs.writeJson(path.join(frontendDir, MOCK_LOCK_FILE), lock, { spaces: 2 });
  const manualNote =
    framework === "next"
      ? `Add rewrites in next.config.js to proxy API calls to http://localhost:${mockPort}`
      : `Add proxy in webpack.config.js devServer to target http://localhost:${mockPort}`;
  return { framework, applied: false, devCommand: null, note: manualNote };
}

/**
 * Undo all proxy changes made by applyMockProxy().
 * Also kills the mock server if its PID was stored in the lock file.
 */
export async function restoreMockProxy(
  frontendDir: string
): Promise<{ restored: boolean; note?: string }> {
  const lockPath = path.join(frontendDir, MOCK_LOCK_FILE);
  if (!(await fs.pathExists(lockPath))) {
    return { restored: false, note: "No lock file found — nothing to restore." };
  }

  const lock: MockLock = await fs.readJson(lockPath);

  for (const action of lock.actions) {
    if (action.type === "wrote-file") {
      const fp = path.join(frontendDir, action.filePath);
      if (await fs.pathExists(fp)) await fs.remove(fp);
    } else if (action.type === "added-pkg-script") {
      const pkgPath = path.join(frontendDir, "package.json");
      if (await fs.pathExists(pkgPath)) {
        const pkg = await fs.readJson(pkgPath);
        if (action.originalValue == null) {
          delete pkg.scripts?.[action.key];
        } else {
          pkg.scripts = pkg.scripts ?? {};
          pkg.scripts[action.key] = action.originalValue;
        }
        await fs.writeJson(pkgPath, pkg, { spaces: 2 });
      }
    } else if (action.type === "patched-pkg-proxy") {
      const pkgPath = path.join(frontendDir, "package.json");
      if (await fs.pathExists(pkgPath)) {
        const pkg = await fs.readJson(pkgPath);
        if (action.originalProxy == null) {
          delete pkg.proxy;
        } else {
          pkg.proxy = action.originalProxy;
        }
        await fs.writeJson(pkgPath, pkg, { spaces: 2 });
      }
    }
  }

  if (lock.mockServerPid) {
    try { process.kill(lock.mockServerPid, "SIGTERM"); } catch { /* already dead */ }
  }

  await fs.remove(lockPath);
  return { restored: true };
}

/**
 * Start mock/server.js as a detached background process.
 * Returns the spawned PID so it can be stored for later cleanup.
 */
export function startMockServerBackground(serverJsPath: string, port: number): number {
  const child = spawn("node", [serverJsPath], {
    detached: true,
    stdio: "ignore",
    env: { ...process.env, MOCK_PORT: String(port) },
  });
  child.unref();
  return child.pid!;
}

/**
 * Save the mock server PID into an existing lock file.
 */
export async function saveMockServerPid(frontendDir: string, pid: number): Promise<void> {
  const lockPath = path.join(frontendDir, MOCK_LOCK_FILE);
  if (await fs.pathExists(lockPath)) {
    const lock: MockLock = await fs.readJson(lockPath);
    lock.mockServerPid = pid;
    await fs.writeJson(lockPath, lock, { spaces: 2 });
  }
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Generate mock server, proxy config, and/or MSW handlers from a SpecDSL.
 * Writes files relative to projectDir.
 */
export async function generateMockAssets(
  dsl: SpecDSL,
  projectDir: string,
  opts: MockServerOptions = {}
): Promise<MockGenerationResult> {
  const port = opts.port ?? 3001;
  const outputDir = path.join(projectDir, opts.outputDir ?? "mock");
  const result: MockGenerationResult = { files: [] };

  await fs.ensureDir(outputDir);

  // 1. Express mock server (always generated)
  const serverJs = generateMockServerJs(dsl, port);
  const serverPath = path.join(outputDir, "server.js");
  await fs.writeFile(serverPath, serverJs, "utf-8");
  result.files.push({
    path: path.relative(projectDir, serverPath),
    description: `Express mock server — run with: node mock/server.js`,
  });

  // README inside mock/
  const mockReadme = `# Mock Server

Auto-generated by \`ai-spec mock\` for **${dsl.feature.title}**.

## Quick start

\`\`\`bash
# Install express (one-time)
npm install --save-dev express

# Start the mock server
node mock/server.js
# → Listening on http://localhost:${port}
\`\`\`

## Endpoints

| Method | Path | Auth | Status |
|--------|------|------|--------|
${dsl.endpoints
  .map(
    (e) =>
      `| ${e.method} | \`${e.path}\` | ${e.auth ? "✓" : "—"} | ${e.successStatus} |`
  )
  .join("\n")}

## Error simulation

Append \`?simulate_error=1\` to any request to test error handling (not yet auto-wired — edit server.js manually).
`;
  const readmePath = path.join(outputDir, "README.md");
  await fs.writeFile(readmePath, mockReadme, "utf-8");
  result.files.push({
    path: path.relative(projectDir, readmePath),
    description: "Mock server usage guide",
  });

  // 2. Proxy config (optional)
  if (opts.proxy) {
    const { content, filename } = generateProxyConfig(dsl, port, projectDir);
    const proxyPath = path.join(projectDir, filename);
    await fs.ensureDir(path.dirname(proxyPath));
    await fs.writeFile(proxyPath, content, "utf-8");
    result.files.push({
      path: filename,
      description: "Proxy config snippet — copy instructions into your framework config",
    });
  }

  // 3. MSW handlers (optional)
  if (opts.msw) {
    const mswDir = path.join(projectDir, "src", "mocks");
    await fs.ensureDir(mswDir);

    const handlersContent = generateMswHandlers(dsl);
    const handlersPath = path.join(mswDir, "handlers.ts");
    await fs.writeFile(handlersPath, handlersContent, "utf-8");
    result.files.push({
      path: path.relative(projectDir, handlersPath),
      description: "MSW request handlers",
    });

    const browserContent = generateMswBrowser();
    const browserPath = path.join(mswDir, "browser.ts");
    await fs.writeFile(browserPath, browserContent, "utf-8");
    result.files.push({
      path: path.relative(projectDir, browserPath),
      description: "MSW browser worker setup",
    });
  }

  return result;
}

/**
 * Find the latest DSL file in a project directory.
 * Looks for *.dsl.json files under .ai-spec/
 */
export async function findLatestDslFile(projectDir: string): Promise<string | null> {
  const specDir = path.join(projectDir, ".ai-spec");
  if (!(await fs.pathExists(specDir))) return null;

  const allFiles: string[] = [];

  async function scan(dir: string): Promise<void> {
    const entries = await fs.readdir(dir);
    for (const entry of entries) {
      const abs = path.join(dir, entry);
      const stat = await fs.stat(abs);
      if (stat.isDirectory()) {
        await scan(abs);
      } else if (entry.endsWith(".dsl.json")) {
        allFiles.push(abs);
      }
    }
  }

  await scan(specDir);

  if (allFiles.length === 0) return null;

  // Return most recently modified
  const withMtimes = await Promise.all(
    allFiles.map(async (f) => ({ f, mtime: (await fs.stat(f)).mtime }))
  );
  withMtimes.sort((a, b) => b.mtime.getTime() - a.mtime.getTime());
  return withMtimes[0].f;
}
